### ISSUE TITLE
[Meta] Synthèse des améliorations & correctifs au support GBFS

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1378]
Je regroupe dans ce ticket l'ensemble des points GBFS au fur et à mesure que je découvre et améliore cette partie, pour faire un suivi simplifié:

* [x] Correction hrefs cassées dans l'index principal GBFS json #1364 - je ne connais pas l'impact en pratique (si c'est très utilisé ou pas etc), peut-être mineur, c'est corrigé
* [x] Correctifs suite au passage en mode Umbrella (impossibilité de lancer les tests de façon isolée) #1374
* [ ] Enquête à mener: je me demande si Sentry est bien effectif sur la partie GBFS. En effet, on reçoit des alertes UptimeRobot (HTTP non 200) fréquemment pour cette partie, et pour autant rien (sauf erreur) n'arrive dans Sentry. À première lecture du code, il y a de bonnes chances que Sentry ne soit pas "pluggé" comme il faut. ~~Il est probable qu'il y aie en fait des erreurs de type "timeout", qui génère des exceptions non actuellement traitées etc (qu'il faudra gérer en mode 502 Bad Gateway probablement)~~. J'enquêterai.
* [ ] J'ai l'impression qu'en cas de retour HTTP != 200 d'un fournisseur, nous retournons malgré tout un code 200, ce qui n'est pas ergonomique pour le consommateur. Je n'en suis pas sûr à 100% mais j'en ai l'impression en ayant travaillé sur des tests, il faudra enquêter, et probablement propager le code fourni par la tierce partie -> confirmé voir #1379
* [x] Implémentation de cache: après avoir étudié Varnish (inutilisable sur le setup, j'expliquerai pourquoi), j'ai un WIP de caching sous forme de plug [ici](https://github.com/etalab/transport-site/compare/gbfs-caching). Il reste des points à traiter, notamment pour voir comment traiter la réponse si le code est non 200, et voir ce qui se passe en cas d'erreur type timeout. Voir #1380 
* [ ] Seule la partie VCUB est sous tests, il sera bon d'en ajouter pour les autres fournisseurs à l'occasion (mais il est plus important et rentable d'avoir Sentry en place si il est désactivé)

A suivre, je complèterai.

**Comment by antoine-de** [comment]
je coche la partie cache vu que c'est implémenté dans #1380
