### ISSUE TITLE
Amélioration de la présentation des ressources d'un dataset

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1454]
## Problématique

On se dit qu'on pourrait encore améliorer la présentation des ressources sur la page `/dataset`

Les problèmes : 
    - ressources communautaires peu claires (surtout en ce qui concerne les ressources générées par transport.data.gouv)
    - comment gérer les GTFS multiples
    - comment gérer les GTFS périmés
    - comment gérer les autres formats (CSV, GeoJSON...)
    

## Solutions
À la suite de l'atelier on se dit qu'on va tester 3 solutions (je fais des sous issues pour que ca soit plus simple niveau dev):

* [ ] Amélioration des catégories de ressources (#1451)
* [ ] Cacher les ressources communautaires générées par le PAN (#1452)
* [ ] Amélioration de la barre de navigation à gauche (#1453)

Pour toutes ces taches ca peut etre cool de garder en tête les différentes typologies de page `/dataset`

* [la classique avec 1 seul GTFS](https://transport.data.gouv.fr/datasets/liste-des-arrets-horaires-et-parcours-de-tous-les-bus-et-tramways-circulant-sur-le-territoire-de-brest-metropole/)
* [celle avec tout plein de GTFS](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1)
* [celle avec 1 GTFS et 1 NeTEx officiel](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-dor-nva-m/metropole/)
* [celle avec des GTFS-RT](https://transport.data.gouv.fr/datasets/reseau-de-transports-en-commun-de-la-communaute-dagglomeration-de-lauxerrois/)
* [celle avec tout plein de GTFS en erreur](https://transport.data.gouv.fr/datasets/donnees-du-reseau-tao-au-format-gtfs-orleans-metropole)
* [celle avec des données non TC (du GBFS par exemple](https://transport.data.gouv.fr/datasets/velos-libre-service-mulhouse-velocite-disponibilite-en-temps-reel/))
* [celle avec des données non TC (des bornes IRVE par exemple](https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques))
* [celle avec des données non TC (du covoit par exemple](https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-covoiturage/))
* [celle avec des données non TC (des parking par exemple](https://transport.data.gouv.fr/datasets/parkings-relais-toulouse-metropole/))
