### ISSUE TITLE
Publish improved datasets

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#158]
[Check this theme in the roadmap](https://trello.com/c/xWGGLka7/10-reusers-publish-improved-datasets)

**Definiton of done**

- [x] I can post a dataset #167
- [x] I can create an organisation if I don't have one #167
- [x] I can have a feedback everything went ok #167
- [x] I can see the modification I did in the list of datasets #171
- [ ] Create community resource endpoint in Elixir app #172
- [ ] Use community resource endpoint to consume them in front #277
- [ ] Make it pretty 😃 #276

**Comment by Tristramg** [comment]
How will this relate with #279 ?

Should we still allow publishing modified version through transport site?

My first reaction would be yes: it is important to establish a strong ownership for the initial producer. Consumer-improver can be anyone, so this should be more seamless and they might even not know about data.gouv.fr
