### ISSUE TITLE
[Meta] Besoins "proxy" court terme

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1586]
En lien avec la "doctrine proxy" [en cours de formalisation](https://github.com/etalab/transport_deploy/issues/27), voici un recueil des besoins court terme sur le sujet du proxy Elixir:

- [x] Faire proxy sur du GTFS-RT (voir https://github.com/etalab/transport_deploy/issues/22) - en cours dans #1559 
- [ ] Faire proxy sur du FTP (voir https://github.com/etalab/transport-site/issues/1033) - spike déjà effectuée, plutôt facile à faire à partir de là
- [x] Faire proxy sur les fichiers CSV GitHub (problème de téléchargement en onglet)
- [ ] Remonter des statistiques d'usage pour pouvoir rassurer les producteurs et "enlever les roulettes" ; on pourrait s'appuyer sur Matomo (voir [code data gouv](https://github.com/opendatateam/udata-piwik/blob/0fe80adc364a227da2f881aec18cac9914e4cdca/udata_piwik/tasks.py#L49) et https://github.com/openfisca/tracker/blob/master/openfisca_tracker/piwik.py)

Ce sont uniquement les points en cours plus ou moins d'exécutions ou planifiés à court terme.

Pour l'instant je regroupe ces points ici, mais peut-être qu'on utilisera un label "proxy" directement à terme, selon comment cela évolue.

Ne sont pas priorisés les points suivants (mais à voir dans le futur):

- Proxy SIRI (https://github.com/etalab/transport-site/issues/1562)

**Comment by thbar** [comment]
On a des métriques à présent, il n'y a pas de gros besoin nouveau qui ressort franchement actuellement, donc je clôture.
