### ISSUE TITLE
[WIP] Liste des warnings Elixir

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1691]
Je fais une méta-issue relative à #1683, mais pas seulement, où je vais lister les warnings individuellement ici. Ca permettra de faire un suivi car il y en a beaucoup, et aussi de faciliter le traitement ou individuellement, ou par groupes, via différentes PR.

- [x] `no configuration found for otp_app :unlock and module Unlock.Endpoint` #1683
- [ ] `warning: :pool_timeout option no longer has an effect and has been replaced with an improved queuing system.
See "Queue config" in DBConnection.start_link/2 documentation for more information.` (vu en production via iex)
- [x] `===> Compiling ranch
src/ranch_ssl.erl:142:7: Warning: ssl:ssl_accept/3 is removed; use ssl_handshake/1,2,3 instead` -> il faut mettre `ranch` à jour https://github.com/ninenines/ranch/issues/314 (traité dans #1683)
- [x] `===> Compiling mochiweb
src/mochiweb_session.erl:145:13: Warning: crypto:block_encrypt/4 is removed; use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead`, voir `mix deps.tree | grep mochi -C 1`, `mochiweb` est une dépendance de `html_sanitize_ex`
- [x] `==> elixir_uuid
Compiling 1 file (.ex)
warning: :crypto.hash/2 defined in application :crypto is used by the current application but the current application does not depend on :crypto. To fix this, you must do one of:` -> il y aurait un fix ici https://github.com/zyro/elixir-uuid/pull/53 mais non mergé, et le mainteneur ne répond pas. Cette dépendance est pullée par `exshape`, je dois vérifier si on peut la supprimer potentiellement -> EDIT: oui je la supprime ici https://github.com/etalab/transport-site/pull/1695
- [ ] `==> vex
Compiling 25 files (.ex)
warning: do not use "length(errors) > 0" to check if a list is not empty since length always traverses the whole list. Prefer to pattern match on a non-empty list, such as [_ | _], or use "errors != []" as a guard
  lib/vex.ex:15
warning: module attribute @only was set but never used
  lib/vex/blank.ex:2` voir https://github.com/CargoSense/vex/issues/68
- [x] Cachex -> nombreux warnings ; traité dans #1698 
- [ ] parallel stream (pas bloquant, voir https://github.com/beatrichartz/parallel_stream/issues/13 et https://github.com/beatrichartz/parallel_stream/pull/16)
- [ ] `==> tzdata
warning: :random.uniform/1 is deprecated. Use the 'rand' module instead
  lib/tzdata/data_loader.ex:17: Tzdata.DataLoader.download_new/1` et beaucoup d'autres #1700 https://github.com/lau/tzdata/pull/106
- [ ] exvcr #1703
- [ ] exaws #1703
- [ ] crontab
- [ ] html_sanitize_ex
- [ ] swarm
- [ ] quantum
- [ ] plug
- [ ] phoenix_markdown
- [ ] scrivener_html
- [ ] notre propre application

### Logs actuels

Au commit 4b3c89c901884c90787c8e8448532f971381703d, on avait encore les logs suivants:

<details>
  <summary>Click to expand!</summary>

```
❯ mix test 2>&1 | tee warnings.log
==> exactor
Compiling 10 files (.ex)
Generated exactor app
==> earmark_parser
Compiling 3 files (.erl)
Compiling 32 files (.ex)
Generated earmark_parser app
==> jumper
Compiling 1 file (.ex)
Generated jumper app
===> Fetching rebar3_hex v6.11.5
===> Fetching hex_core v0.7.1
===> Fetching verl v1.0.2
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
_build/default/plugins/rebar3_hex/src/rebar3_hex_repo.erl:128:32: Warning: public_key:ssh_encode/2 is deprecated and will be removed in OTP 26; use ssh_file:encode/2 instead

===> Analyzing applications...
===> Compiling p1_utils
==> nimble_options
Compiling 3 files (.ex)
Generated nimble_options app
===> Analyzing applications...
===> Compiling parse_trans
==> gen_state_machine
Compiling 3 files (.ex)
Generated gen_state_machine app
==> sizeable
Compiling 1 file (.ex)
Generated sizeable app
==> unsafe
Compiling 3 files (.ex)
Generated unsafe app
==> vex
Compiling 25 files (.ex)
Generated vex app
===> Analyzing applications...
===> Compiling yamerl
===> Analyzing applications...
===> Compiling mimerl
==> nimble_pool
Compiling 2 files (.ex)
Generated nimble_pool app

09:30:24.449 [info]  Compiling file system watcher for Mac...

09:30:25.723 [info]  Done.
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> connection
Compiling 1 file (.ex)
Generated connection app
===> Fetching rebar3_hex v6.11.5
===> Fetching hex_core v0.7.1
===> Fetching verl v1.0.2
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
_build/default/plugins/rebar3_hex/src/rebar3_hex_repo.erl:128:32: Warning: public_key:ssh_encode/2 is deprecated and will be removed in OTP 26; use ssh_file:encode/2 instead

===> Analyzing applications...
===> Compiling sleeplocks
===> Analyzing applications...
===> Compiling metrics
===> Analyzing applications...
===> Compiling unicode_util_compat
===> Analyzing applications...
===> Compiling idna
==> bunt
Compiling 2 files (.ex)
Generated bunt app
==> gettext
Compiling 1 file (.yrl)
Compiling 1 file (.erl)
Compiling 20 files (.ex)
Generated gettext app
==> gen_stage
Compiling 10 files (.ex)
Generated gen_stage app
===> Fetching rebar3_hex v6.11.5
===> Fetching hex_core v0.7.1
===> Fetching verl v1.0.2
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
_build/default/plugins/rebar3_hex/src/rebar3_hex_repo.erl:128:32: Warning: public_key:ssh_encode/2 is deprecated and will be removed in OTP 26; use ssh_file:encode/2 instead

===> Fetching pc v1.13.0
===> Analyzing applications...
===> Compiling pc
===> Compiling c_src/iconv.c
===> Linking /Users/thbar/git/transport/transport-site/deps/iconv/priv/lib/iconv.so
===> Analyzing applications...
===> Compiling iconv
===> Analyzing applications...
===> Compiling ranch
===> Analyzing applications...
===> Compiling telemetry
===> Analyzing applications...
===> Compiling meck
==> mock
Compiling 1 file (.ex)
Generated mock app
==> eternal
Compiling 5 files (.ex)
Generated eternal app
==> cachex
Compiling 54 files (.ex)
Generated cachex app
==> decimal
Compiling 4 files (.ex)
Generated decimal app
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of ASCII letters, numbers, and underscores do not require quotes
  /Users/thbar/git/transport/transport-site/deps/parallel_stream/mix.exs:17

==> parallel_stream
Compiling 11 files (.ex)
warning: Stream.chunk/4 is deprecated. Use Stream.chunk_every/4 instead
  lib/parallel_stream/producer.ex:16: ParallelStream.Producer.build!/4

Generated parallel_stream app
==> jason
Compiling 8 files (.ex)
Generated jason app
==> recon
Compiling 6 files (.erl)
Generated recon app
==> ssl_verify_fun
Compiling 7 files (.erl)
Generated ssl_verify_fun app
==> yaml_elixir
Compiling 6 files (.ex)
Generated yaml_elixir app
==> scrivener
Compiling 4 files (.ex)
Generated scrivener app
==> exconstructor
Compiling 1 file (.ex)
Generated exconstructor app
==> html_entities
Compiling 2 files (.ex)
Generated html_entities app
==> floki
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 24 files (.ex)
Generated floki app
==> combine
Compiling 6 files (.ex)
Generated combine app
==> castore
Compiling 1 file (.ex)
Generated castore app
==> mint
Compiling 1 file (.erl)
Compiling 23 files (.ex)
Generated mint app
==> finch
Compiling 10 files (.ex)
Generated finch app
==> unidecode
Compiling 2 files (.ex)
Compiling lib/unidecode/decoder.ex (it's taking more than 10s)
Generated unidecode app
==> csv
Compiling 10 files (.ex)
Generated csv app
==> mox
Compiling 3 files (.ex)
Generated mox app
==> jsx
Compiling 9 files (.erl)
Generated jsx app
==> exjsx
Compiling 1 file (.ex)
Generated exjsx app
===> Analyzing applications...
===> Compiling certifi
===> Analyzing applications...
===> Compiling hackney
==> excoveralls
Compiling 27 files (.ex)
Generated excoveralls app
==> tzdata
Compiling 17 files (.ex)
warning: unknown compiler variable "______" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
  lib/tzdata/parser.ex:27: Tzdata.Parser.process_tz_list/1

warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
Found at 2 locations:
  lib/tzdata/tzdata_app.ex:10: Tzdata.App.start/2
  lib/tzdata/tzdata_app.ex:13: Tzdata.App.start/2

warning: :random.uniform/1 is deprecated. Use the 'rand' module instead
  lib/tzdata/data_loader.ex:17: Tzdata.DataLoader.download_new/1

Generated tzdata app
==> timex
Compiling 58 files (.ex)
Generated timex app
==> earmark
Compiling 9 files (.ex)
Generated earmark app
==> sweet_xml
Compiling 2 files (.ex)
Generated sweet_xml app
==> ex_aws
Compiling 26 files (.ex)
Generated ex_aws app
==> ex_aws_s3
Compiling 7 files (.ex)
Generated ex_aws_s3 app
==> db_connection
Compiling 14 files (.ex)
Generated db_connection app
==> httpoison
Compiling 3 files (.ex)
Generated httpoison app
==> exvcr
Compiling 30 files (.ex)
warning: redefining @doc attribute previously set at line 35.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:

    @doc """
    new docs
    """
    def filter_request_headers(...)

  lib/exvcr/config.ex:42: ExVCR.Config.filter_request_headers/1

warning: redefining @doc attribute previously set at line 50.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:

    @doc """
    new docs
    """
    def filter_request_options(...)

  lib/exvcr/config.ex:57: ExVCR.Config.filter_request_options/1

warning: redefining @doc attribute previously set at line 27.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:

    @doc """
    new docs
    """
    def use_cassette(...)

  lib/exvcr/mock.ex:48: ExVCR.Mock.use_cassette/3

warning: :hackney_request.encode_form/1 defined in application :hackney is used by the current application but the current application does not depend on :hackney. To fix this, you must do one of:

  1. If :hackney is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :hackney is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :hackney, you may optionally skip this warning by adding [xref: [exclude: [:hackney_request]]] to your "def project" in mix.exs

  lib/exvcr/adapter/hackney/converter.ex:104: ExVCR.Adapter.Hackney.Converter.parse_request_body/1

Generated exvcr app
==> credo
Compiling 214 files (.ex)
Generated credo app
==> ecto
Compiling 56 files (.ex)
Generated ecto app
==> crontab
Compiling 7 files (.ex)
warning: Code.ensure_compiled?/1 is deprecated. Use Code.ensure_compiled/1 instead (see the proper disclaimers in its docs)
  lib/crontab/cron_expression/ecto_type.ex:1

warning: function head for def matches_date?/2 must come at the top of its direct implementation. Instead of:

    def add(a, b), do: a + b
    def add(a, b)

one should write:

    def add(a, b)
    def add(a, b), do: a + b

  lib/crontab/date_checker.ex:39

warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module Crontab.CronExpression.Ecto.Type)
  lib/crontab/cron_expression/ecto_type.ex:2: Crontab.CronExpression.Ecto.Type (module)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module Crontab.CronExpression.Ecto.Type)
  lib/crontab/cron_expression/ecto_type.ex:2: Crontab.CronExpression.Ecto.Type (module)

Generated crontab app
==> typed_ecto_schema
Compiling 4 files (.ex)
Generated typed_ecto_schema app
==> ymlr
Compiling 2 files (.ex)
Generated ymlr app
==> phoenix_pubsub
Compiling 11 files (.ex)
Generated phoenix_pubsub app
==> oauth2
Compiling 13 files (.ex)
Generated oauth2 app
===> Analyzing applications...
===> Compiling mochiweb
==> html_sanitize_ex
Compiling 11 files (.ex)
warning: redefining @doc attribute previously set at line 15.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:

    @doc """
    new docs
    """
    def scrub(...)

  lib/html_sanitize_ex/scrubber/no_scrub.ex:24: HtmlSanitizeEx.Scrubber.NoScrub.scrub/1

warning: redefining @doc attribute previously set at line 15.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:

    @doc """
    new docs
    """
    def scrub(...)

  lib/html_sanitize_ex/scrubber/no_scrub.ex:29: HtmlSanitizeEx.Scrubber.NoScrub.scrub/1

Generated html_sanitize_ex app
===> Analyzing applications...
===> Compiling cowlib
===> Analyzing applications...
===> Compiling cowboy
===> Analyzing applications...
===> Compiling cowboy_telemetry
==> mime
Compiling 2 files (.ex)
Generated mime app
==> libring
Compiling 5 files (.ex)
Generated libring app
==> swarm
Compiling 1 file (.erl)
Compiling 10 files (.ex)
warning: Supervisor.Spec.supervise/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
  lib/swarm/app.ex:16: Swarm.App.init/1

warning: Supervisor.Spec.supervisor/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
  lib/swarm/app.ex:11: Swarm.App.init/1

warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
Found at 2 locations:
  lib/swarm/app.ex:12: Swarm.App.init/1
  lib/swarm/app.ex:13: Swarm.App.init/1

Generated swarm app
==> quantum
Compiling 37 files (.ex)
warning: Code.ensure_compiled?/1 is deprecated. Use Code.ensure_compiled/1 instead (see the proper disclaimers in its docs)
  lib/quantum/date_library/calendar.ex:1

warning: Code.ensure_compiled?/1 is deprecated. Use Code.ensure_compiled/1 instead (see the proper disclaimers in its docs)
  lib/quantum/date_library/timex.ex:1

Generated quantum app
==> postgrex
Compiling 61 files (.ex)
Generated postgrex app
==> ecto_sql
Compiling 26 files (.ex)
Generated ecto_sql app
==> ex_machina
Compiling 5 files (.ex)
Generated ex_machina app
==> plug_crypto
Compiling 5 files (.ex)
Generated plug_crypto app
==> plug
Compiling 1 file (.erl)
Compiling 41 files (.ex)
warning: MIME.valid?/1 is deprecated. Use MIME.extensions(type) != [] instead
  lib/plug/mime.ex:32: Plug.MIME.valid?/1

warning: System.stacktrace/0 is deprecated. Use __STACKTRACE__ instead
  lib/plug/conn/wrapper_error.ex:23: Plug.Conn.WrapperError.reraise/3

Generated plug app
==> phoenix_html
Compiling 8 files (.ex)
Generated phoenix_html app
==> plug_cowboy
Compiling 5 files (.ex)
Generated plug_cowboy app
==> phoenix
Compiling 66 files (.ex)
Generated phoenix app
==> phoenix_markdown
Compiling 2 files (.ex)
warning: Earmark.as_html!/2 defined in application :earmark is used by the current application but the current application does not depend on :earmark. To fix this, you must do one of:

  1. If :earmark is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :earmark is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :earmark, you may optionally skip this warning by adding [xref: [exclude: [Earmark]]] to your "def project" in mix.exs

  lib/phoenix_markdown/engine.ex:35: PhoenixMarkdown.Engine.compile/2

warning: HtmlEntities.decode/1 defined in application :html_entities is used by the current application but the current application does not depend on :html_entities. To fix this, you must do one of:

  1. If :html_entities is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :html_entities is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :html_entities, you may optionally skip this warning by adding [xref: [exclude: [HtmlEntities]]] to your "def project" in mix.exs

  lib/phoenix_markdown/engine.ex:58: PhoenixMarkdown.Engine.do_restore_smart_tags/2

Generated phoenix_markdown app
==> phoenix_live_view
Compiling 22 files (.ex)
Generated phoenix_live_view app
==> sentry
Compiling 16 files (.ex)
Generated sentry app
==> scrivener_html
Compiling 2 files (.ex)
warning: Phoenix.Naming.resource_name/1 defined in application :phoenix is used by the current application but the current application does not depend on :phoenix. To fix this, you must do one of:

  1. If :phoenix is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.Naming]]] to your "def project" in mix.exs

  lib/scrivener/html.ex:178: Scrivener.HTML.name_for/2

warning: Phoenix.HTML.__using__/1 defined in application :phoenix_html is used by the current application but the current application does not depend on :phoenix_html. To fix this, you must do one of:

  1. If :phoenix_html is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix_html is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix_html, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.HTML]]] to your "def project" in mix.exs

Found at 2 locations:
  lib/scrivener/html.ex:2: Scrivener.HTML
  lib/scrivener/html/seo.ex:15: Scrivener.HTML.SEO

warning: Phoenix.HTML.raw/1 defined in application :phoenix_html is used by the current application but the current application does not depend on :phoenix_html. To fix this, you must do one of:

  1. If :phoenix_html is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix_html is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix_html, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.HTML]]] to your "def project" in mix.exs

Found at 3 locations:
  lib/scrivener/html.ex:11: Scrivener.HTML
  lib/scrivener/html.ex:123: Scrivener.HTML.pagination_links/4
  lib/scrivener/html.ex:639: Scrivener.HTML.safe/1

warning: Phoenix.HTML.Link.link/2 defined in application :phoenix_html is used by the current application but the current application does not depend on :phoenix_html. To fix this, you must do one of:

  1. If :phoenix_html is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix_html is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix_html, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.HTML.Link]]] to your "def project" in mix.exs

Found at 2 locations:
  lib/scrivener/html.ex:344: Scrivener.HTML.page/7
  lib/scrivener/html.ex:374: Scrivener.HTML.page/7

warning: Phoenix.HTML.Tag.content_tag/2 defined in application :phoenix_html is used by the current application but the current application does not depend on :phoenix_html. To fix this, you must do one of:

  1. If :phoenix_html is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix_html is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix_html, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.HTML.Tag]]] to your "def project" in mix.exs

  lib/scrivener/html.ex:204: Scrivener.HTML._pagination_links/2

warning: Phoenix.HTML.Tag.content_tag/3 defined in application :phoenix_html is used by the current application but the current application does not depend on :phoenix_html. To fix this, you must do one of:

  1. If :phoenix_html is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix_html is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix_html, you may optionally skip this warning by adding [xref: [exclude: [Phoenix.HTML.Tag]]] to your "def project" in mix.exs

Found at 18 locations:
  lib/scrivener/html.ex:205: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:222: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:223: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:240: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:256: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:272: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:288: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:289: Scrivener.HTML._pagination_links/2
  lib/scrivener/html.ex:313: Scrivener.HTML.page/7
  lib/scrivener/html.ex:319: Scrivener.HTML.page/7
  lib/scrivener/html.ex:322: Scrivener.HTML.page/7
  lib/scrivener/html.ex:340: Scrivener.HTML.page/7
  lib/scrivener/html.ex:351: Scrivener.HTML.page/7
  lib/scrivener/html.ex:365: Scrivener.HTML.page/7
  lib/scrivener/html.ex:370: Scrivener.HTML.page/7
  lib/scrivener/html.ex:383: Scrivener.HTML.page/7
  lib/scrivener/html/seo.ex:84: Scrivener.HTML.SEO.prev_header_link/4
  lib/scrivener/html/seo.ex:89: Scrivener.HTML.SEO.next_header_link/4

warning: Plug.Conn.Query.encode/1 defined in application :plug is used by the current application but the current application does not depend on :plug. To fix this, you must do one of:

  1. If :plug is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :plug is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :plug, you may optionally skip this warning by adding [xref: [exclude: [Plug.Conn.Query]]] to your "def project" in mix.exs

  lib/scrivener/html.ex:60: Scrivener.HTML.Default.path/3

Generated scrivener_html app
==> open_api_spex
Compiling 70 files (.ex)
Generated open_api_spex app
==> cors_plug
Compiling 1 file (.ex)
Generated cors_plug app
==> bypass
Compiling 5 files (.ex)
Generated bypass app
==> scrivener_ecto
Compiling 2 files (.ex)
Generated scrivener_ecto app
==> scrivener_list
Compiling 1 file (.ex)
Generated scrivener_list app
==> geo
Compiling 26 files (.ex)
Generated geo app
==> geo_postgis
Compiling 4 files (.ex)
Generated geo_postgis app
==> phoenix_ecto
Compiling 7 files (.ex)
Generated phoenix_ecto app
==> unlock
Compiling 9 files (.ex)
Generated unlock app
==> shared
Compiling 7 files (.ex)
Generated shared app
==> datagouvfr
Compiling 17 files (.ex)
Generated datagouvfr app
==> db
Compiling 19 files (.ex)
Generated db app
==> gbfs
Compiling 17 files (.ex)
Generated gbfs app
==> transport
Compiling 96 files (.ex)
warning: Supervisor.Spec.supervisor/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
Found at 2 locations:
  lib/transport/application.ex:21: Transport.Application.start/2
  lib/transport/application.ex:22: Transport.Application.start/2

warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
  lib/transport/application.ex:38: Transport.Application.add_scheduler/1

Generated transport app

09:32:23.774 [info]  == Running 20210630130031 DB.Repo.Migrations.AddResourceSchema.change/0 forward

09:32:23.774 [info]  alter table resource

09:32:23.778 [info]  == Migrated 20210630130031 in 0.0s
==> unlock
Excluding tags: [:pending]

***...*.

Finished in 0.06 seconds (0.00s async, 0.06s sync)
8 tests, 0 failures, 4 skipped

Randomized with seed 362154
==> shared
Excluding tags: [:pending]

.........

Finished in 0.1 seconds (0.1s async, 0.00s sync)
2 doctests, 7 tests, 0 failures

Randomized with seed 362154
==> datagouvfr
Excluding tags: [:pending]

...

Finished in 0.5 seconds (0.00s async, 0.5s sync)
3 tests, 0 failures

Randomized with seed 362154
==> db
Excluding tags: [:pending]

.09:32:26.378 [warn] error while importing dataset: %{region: ["You need to fill either aom, region or use datagouv's zone"]}
...09:32:26.593 [warn] error while importing dataset: %{region: ["You need to fill either aom, region or use datagouv's zone"]}
..09:32:26.660 [warn] error while importing dataset: %{region: ["You need to fill either aom, region or use datagouv's zone"], slug: ["can't be blank"]}
.09:32:26.687 [warn] error while importing dataset: %{region: ["You need to fill either aom, region or use datagouv's zone"]}
........

Finished in 1.7 seconds (0.00s async, 1.7s sync)
15 tests, 0 failures

Randomized with seed 362154
==> gbfs
Excluding tags: [:pending]

....09:32:27.241 request_id=Fo_AaOQi4AhMiwAAAnoJ [error] impossible to query jcdecaux: {:ok, %HTTPoison.Response{body: "{}", headers: [], request: nil, request_url: nil, status_code: 500}}
......09:32:27.508 request_id=Fo_AaPQJ81jxUgYAAnpJ [error] impossible to query vcub: {:ok, %HTTPoison.Response{body: "{}", headers: [], request: nil, request_url: nil, status_code: 500}}
.....09:32:27.838 request_id=Fo_AaQfE3oD4598AA5ZG [error] impossible to query jcdecaux: {:ok, %HTTPoison.Response{body: "{}", headers: [], request: nil, request_url: nil, status_code: 500}}
...

Finished in 1.0 seconds (0.1s async, 0.8s sync)
19 tests, 0 failures, 1 excluded

Randomized with seed 362154
==> transport
Excluding tags: [:external, :pending]

.......................................................................09:32:31.894 [warn] Cannot process nil url (url) at the moment. Skipping.
.............................................................

Finished in 11.5 seconds (1.2s async, 10.3s sync)
48 doctests, 100 tests, 0 failures, 16 excluded

Randomized with seed 362154
```  
</details>
