### ISSUE TITLE
Validation-driven communication I

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#179]
[Check this theme in the roadmap](https://trello.com/c/dtBKpTip/14-reusers-talk-to-producers)

**Definition of done**

_From the user's perspective_

- [x] I can leave a message on a dataset by error type #180
- [x] I see the message I left when I select the error type #181
- [ ] I don't see other errors' messages when I select the error type #182 
- [ ] I know how long has it been since I published the message #143

_From a system's perspective_

- [x] Make sure we can create discussions by error types opendatateam/udata#1360
