### ISSUE TITLE
Architecture V2

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1806]
Meta-issue sur le passage de notre application vers l'architecture V2.
Issue qui sera amenée à être détaillée au fut et à mesure de l'avancement des tâches.
Board Miro qui nous sert à brainstormer sur le sujet : https://miro.com/app/board/o9J_lHuNE1M=/

- [x] Lancer le convertisseur geojson depuis l'appli #1782 
- [ ] Historiser les données GTFS de façon améliorée #1921 #1937 (reste #1964 et #1965)
- [ ] Tester le validateur GTFS de mobility data #1805 
- [ ] Remplacer le code Python de conversion et publication vers data.gouv par du code côté Elixir (à découper en tâches sur Miro)
- [ ] Intégrer le validateur de GTFS de Mobility Data au site (à découper en tâches sur Miro)
- [ ] ...

**Comment by AntoineAugusti** [comment]
Je vais fermer cette issue, ça fait bien longtemps qu'on utilise Oban en production y compris en lançant des binaires
