### ISSUE TITLE
[EPIC] passage en revue du scan dashlord

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1814]
Notre site est scanné ici par la MTE-MCTRT:

https://dashlord.mte.incubateur.net/#/url/https%3A%2F%2Ftransport.data.gouv.fr

On a plusieurs points d'améliorations (connus mais on n'avait pas créé de ticket avant, j'en profite), en synthèse:
- [ ] Performance générale de la home (note: ça pourrait être géré conjointement avec le passage à `esbuild` en Phoenix 1.6
- [ ] Gestion TLS (à gérer au niveau de notre hébergeur) capée à B seulement
- [ ] Content Security Policy header non implémenté
- [ ] X-Frame-Options
- [ ] Et autres alertes OWASP

Attention ça peut être un trou sans fin et il faut bien évaluer le bénéfice de chaque correctif et mettre un coût en face, toutefois il est également important de mettre en visibilité ces points et de travailler graduellement à les améliorer.

Ceci est encore plus vrai du fait que nous travaillons sur l'audit de conformité (#1558).

**Comment by thbar** [comment]
Pour info @andlio @fchabouis @AntoineAugusti

**Comment by AntoineAugusti** [comment]
Pour SSL on est maintenant A+, https://dashlord.mte.incubateur.net/dashlord/url/transport-data-gouv-fr/securite/

**Comment by thbar** [comment]
Il y aurait toujours des points à améliorer !
