### ISSUE TITLE
Data validation: from curated datasets

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#183]
[Check this theme in the roadmap](https://trello.com/c/cPhd4B3O/17-data-validation-from-curated-datasets)

**Definition of done**

- [x] Update curated list of datasets #216 #196 
- [x] I can validate datasets in the curated list with _datatools_ #178
- [x] I can launch those validation tasks with a script #185
- [x] I can query an API to obtain a dataset's latest validation results #186
- [x] I can provision that API automatically (with _Ansible_ or a similar tool) #184
