### ISSUE TITLE
Create deployment script for datatools

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#184]
Relates to #183

**Definition of done:**

- [x] Instance docker pour CircleCI etalab/transport-ops#1
- [x] Publish docker and plug into CircleCI etalab/transport-site#271
- [x] Transport's clevercloud account
- [x] Add credentials
- [x] Production instance with a deployment tool etalab/transport-datatools-server#24
- [x] Configure DNS (datatools.transport.data.gouv.fr)
- [x] Handle HTTPS certifcate
- [x] Document the deployment process etalab/transport-ops#6
- [x] Set up a clean fork
- [x] Manage CORS issues
