### ISSUE TITLE
Add mix task to validate with datatools

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#185]
Relates to #183

- [x] Add task to validate datasets #244 
- [x] Add task to retrieve validation results #244 
- [x] Clean up Google's gtfs-validator code #238
