### ISSUE TITLE
Invite entrepreneurs to use the data

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#22]
**Story :**

    When the Transport team direct me to transport.beta.gouv.fr
    I want to have an easy way to explore which data is available,
    and be able to download it,
    so I can quickly integrate to my product(s).

**Definition of done**:

- [x] I can click somewhere to explore the available datasets #42 #46
- [x] There's a list of available, usable data #46
- [x] I can know the coverage of the data #46
- [x] I can know the LICENSE #46
- [x] I can know the format #46
- [x] I can know how to contact the AO #46
- [x] I can click somewhere to download the dataset(s) #46

**Mockup :**

![image uploaded from ios](https://user-images.githubusercontent.com/329236/30814048-5910b938-a20f-11e7-85b0-86fc087b2966.jpg)
