### ISSUE TITLE
Migrer historisation vers resource_id

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2410]
Le système d'historisation actuel se repose sur `resource.datagouv_id` comme clé étrangère, ce qui pose plusieurs limitations comme https://github.com/etalab/transport-site/issues/1930.

L'objectif est de migrer vers `resource.id` comme clé étrangère, pour plus coller à notre modèle de données.

Ce ticket permet de lier les différentes pull-requests nécessaires à cette migration et de garder des notes.

- [x] Ajouter une colonne `resource_id` #2411 
- [x] Remplir `resource_id` pour les lignes existantes https://github.com/etalab/transport-site/pull/2418
- [x] Adapter le code source existant pour utiliser `resource_id` https://github.com/etalab/transport-site/pull/2451
- [ ] Supprimer la colonne `datagouv_id` ?

**Comment by thbar** [comment]
Est-ce qu'on prévoit un backfill mentionné ici en todo peut-être ?

**Comment by AntoineAugusti** [comment]
[Remarque de @fchabouis](https://mattermost.incubateur.net/betagouv/pl/w6nmcjdk4ibn7d8bij1eikeskw) concernant le remplissage de `resource_id`.

---

Si un producteur change l'url d'une ressource, chez nous ça va se traduire par une suppression d'une ressource, et par la création d'une nouvelle ressource. Un resource_id qui disparait et un qui apparait. Donc de base, on va avoir des resource_id dans resource_history qui n'auront plus leur ressource correspondante.

Le problème c'est pas qu'on ne sait plus faire le lien entre resource_history et resource, c'est que parfois la resource_history est orpheline. Mais si on a le dataset_id, c'est quand meme utile.

Pour moi je vois 2 grands cas d'usage des resource_history :

- je veux toutes les resources history actuelles d'un dataset (par exemple sur la page détail des datasets). Du coup je fais une jointure dataset <> resource <> resource_history (puis multi_validation par exemple)
- je veux afficher l'historique des ressources qui sont rattachées à un dataset, par exemple pour les afficher sur la page dataset dans la section historique". Du coup je vais faire select * from resource_history where dataset_id = XXX et là je passe pas par le resource_id sinon je vais en oublier.

**Comment by AntoineAugusti** [comment]
Je viens de faire le backill de `resource_id` en production.

```bash
clever ssh --alias prod-worker
iex -S mix
iex> Transport.Jobs.Backfill.ResourceHistoryResourceId.new(%{}) |> Oban.insert()
```

puis
```sql
select resource_id is null, count(1)
from resource_history
group by 1
```

|resource_id is null|count|
|--- | ---|
|FALSE | 15554|
|TRUE | 5414|

**Comment by thbar** [comment]
> Je viens de faire le backill de resource_id en production.

Merci @AntoineAugusti !

**Comment by AntoineAugusti** [comment]
Je vais fermer cette issue.

Je n'ai pas supprimé la colonne `datagouv_id`. On pourrait la supprimer tout à fait, elle n'est plus utilisée par le code. Elle ne fait pas de mal en base de données et pourrait même servir pour faire des analyses de stabilité de ressources sur data.gouv.fr je la laisse.

Si @etalab/transport-tech y voit un problème, on en discute !
