### ISSUE TITLE
[Meta] Première ouverture de données SIRI

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2475]
Je regroupe dans ce ticket la roadmap proposée pour l'ouverture des données SIRI.

Le périmètre est de proposer une ouverture "sur étagère" avec un requestor_ref public unique, des jeux de données utilisables, et du mode uniquement pull (request/response), pas d'abonnement pour commencer.

## Roadmap (proposition)

Voilà ce que je propose (je détaillerai chaque item dans une issue spécifique un peu plus tard) :

- [x] Finaliser https://github.com/etalab/transport-site/pull/2459 -> proxy en beta privée, sans protection particulière, pour notre propre usage dans un premier temps. Il restera des TODO dedans etc.
- [x] Déployer la première configuration https://github.com/etalab/transport-proxy-config/pull/45 qui ajoute des endpoints connus
- [x] Demander aux fournisseurs davantage de endpoints SIRI dès à présent. Bien expliquer l'usage cible (test interne, puis publication externe avec accord après)
- [x] Créer une page de requêtage (privée au début, publique après) pour faciliter l'usage par notre équipe déjà, qui créera une requête SIRI pour nous et permettra de la déclencher, en affichant le résultat un peu formatté
  - https://github.com/etalab/transport-site/pull/2704
  - https://github.com/etalab/transport-site/pull/2746
  - https://github.com/etalab/transport-site/pull/2750
  - https://github.com/etalab/transport-site/pull/2760
- [x] Définir un mode opératoire pour une ouverture sans proxy https://github.com/etalab/transport-site/issues/2817
- [ ] Créer un petit test automatisé "de masse" (il y a déjà des bouts pour aller vers ça), qui vérifiera les données disponibles sur un script standardisé (du type: tenter de faire un `GetEstimatedTimetable` sans filtre, voir si le retour est vide ou pas, faire un `LinesDiscovery` si ce n'est pas le cas etc)
- [ ] Modifier le proxy pour être utilisable par le grand public (limitation aux services spécifiés, interdire l'abonnement, ajouter un rate-limit, essayer de cacher le requestor_ref "secret" de la sortie etc) -> voir https://github.com/etalab/transport-site/issues/2476
- [ ] Lancer une vague d'ouverture conjointement avec les AOMs

## Travaux préalables

- [x] https://github.com/etalab/transport-site/issues/2296 -> cette rédaction de design fait suite à de nombreux échanges dans les mois précédents avec des producteurs ayant l'obligation de publier ces données

### Scripts clients

- [x] https://github.com/etalab/transport-site/pull/2063
- [x] https://github.com/etalab/transport-site/pull/2072
- [x] https://github.com/etalab/transport-site/pull/2391
- [x] https://github.com/etalab/transport-site/pull/2397

### Travaux proxy

- [x] https://github.com/etalab/transport-site/pull/2440

**Comment by thbar** [comment]
Plus de proxy, on passe par:
- https://github.com/etalab/transport-site/issues/2817
