### ISSUE TITLE
Run data validation tests without cassettes

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#260]
As of today, `aggregate` and `repository` tests are intertwined. We need to start separating them  order to remove the use of `ExVCR` once transport/transport-ops#1 will be plugged into CircleCI.

- [x] Add CircleCI workflows #271
- [x] Add integration testing for data validation #271
- [x] Add project repo tests #261 
- [ ] Add feed source repo tests
- [ ] Add feed version repo tests
- [ ] Use a behaviour pour tester project aggregate
- [ ] Stop using cassettes for data validation
