### ISSUE TITLE
Publish datasets through data.gouv.fr

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#278]
Superseds #44

[Check this theme in the roadmap](https://trello.com/c/aX6yXAe5/25-publish-datasets-through-datagouvfr)

**Definition of done**

- [x] Remove dataset upload logic #279
- [ ] Improve dataset republishing logic #165
- [ ] Add how-to publish a dataset #280
- [ ] Validate / invalidate with user testing
- [ ] Iterate
- [ ] Done
