### ISSUE TITLE
Allow AOs to log in / sign up

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#29]
When I click to open my data,
    and that I see a page explaining me I'll be redirected to data.gouv.fr,
    I want to understand what's data.gouv.fr,
    and that I want to understand what's the relationship between data.gouv.fr and Transport,
    and that I do not read in english,
    and that I want to know exactly what I'm supposed to do,
    so I can be reassured that I'm doing the right thing,
    and that I wont be left to my fate.

Scénario :

- [x] I can see a log in / sign up link #35
- [x] I have an explanation of what data.gouv.fr is #67 
- [x] I have an explanation of what the relationship is between data.gouv.fr and Transport #67 
- [x] I have an explanation of what's going to happen and what I'm I supposed to do #67 
- [x] The explanations are in french #47 
- [x] I can click somewhere to start the log in / sign up process #40 
- [x] I can click somewhere to ask for help #59 

![image uploaded from ios](https://user-images.githubusercontent.com/329236/30378592-091b190c-9894-11e7-80af-86898a37a6a0.jpg)
