### ISSUE TITLE
Data validation II: in-house validator

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#294]
[Check this theme in the roadmap](https://trello.com/c/JKqGVFWM/28-data-validation-ii-in-house-validator)

**Definition of done**

- [x] Extract the gtfs parsing from csa-rust
- [x] Implement "not used stop" validation
- [x] Use google transitfeedvalidator test set
- [x] Validate via JSON API (sync) etalab/transport-validator-rust#3
- [x] GTFS Validator deployment
- [x] Update data validation tasks #302 
- [x] Save results somewhere (process, ETS or mongo) #303
- [x] Show results in front #310

**Comment by Tristramg** [comment]
I consider this task is completed.
