### ISSUE TITLE
Suivi ajout de contacts et d'abonnements à des notifications

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2993]
- [x] https://github.com/etalab/transport-site/pull/2965
- [x] https://github.com/etalab/transport-site/pull/2981
- [x] https://github.com/etalab/transport-site/pull/2992
- [x] Migration de `Transport.Notifications` qui utilise la configuration YAML pour utiliser contacts et abonnements https://github.com/etalab/transport-site/pull/2994

**Comment by AntoineAugusti** [comment]
Déployé en production, dépôt [transport-notifications](https://github.com/etalab/transport-notifications archivé. 135 contacts et 766 abonnements en base.

Je ferai l'import et le suivi en staging !
