### ISSUE TITLE
Départ de Francis

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#3093]
Je pars fin juin et après 3.5 ans passés ici, je liste dans cette issue tout ce que je veux mettre au propre avant mon départ.
Il peut y avoir des questions de droits à partager ou transférer, ou de la passation à faire sur certains sujets.

- [ ] contribuer.transport.data.gouv.fr (mise à jour des libs, déploiement sur Netlify, compte the-pr-bot)
- [ ] normes.transport.data.gouv.fr (partage des droits sur Netlify)
- [ ] blog.transport.data.gouv.fr (partage des droits sur Netlfify, vérifier que ça marche toujours)
- [ ] validateur GTFS (passation technique, clarifier la future maintenance)
- [ ] Tuiles Mapbox (trouver une solution de rechange ou passer sur un compte non perso et faire payer la facture par Pathtech)
- [ ] ...

**Comment by thbar** [comment]
@fchabouis peut-être as-tu des choses sous Miro perso aussi ?

**Comment by fchabouis** [comment]
> @fchabouis peut-être as-tu des choses sous Miro perso aussi ?

je ne crois pas mais je regarderai

**Comment by fchabouis** [comment]
Je vous lègue mon compte uptimerobot et je vous ai partagé les codes d'accès via Dashlane.
