### ISSUE TITLE
[Epic] Améliorations carte GTFS nationale

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3136]
Tiré de:
- https://github.com/etalab/transport-site/pull/3122

### Points à traiter avant passage en public

- [x] Ajouter un kill-switch de la feature par sécurité (merci @AntoineAugusti) -> `DISABLE_NATIONAL_GTFS_MAP=1`
- [ ] ~~Optimiser la vue détaillée (génération JSON via Postgres ?)~~ on va s'en passer pour le moment
- [ ] ~~Transformer "select count(*) from pg_matviews" en query Ecto (éviter injection SQL)~~
- [x] Extraire le code de création des zoom-levels cachés vers une méthode dédiée (plutôt que de les générer à la volée)
- [x] Implémenter une méthode qui fait "si rien n'existe crée, sinon rafraîchit"
- [x] Appeler cette méthode au bon moment (après consolidation GTFS)
- [x] Créer des tests là où ils manquent (voir coverage)
- [x] Déplacer la carte vers une vue publique
- [x] PR de doc pour `Jason.Fragment.new` qui n'est pas documenté mais m'a aidé (https://github.com/michalmuskala/jason/pull/166)
- [ ] ~~Filtrer sur la période de validité (ex: https://github.com/etalab/transport-qualite-des-donnees/issues/11)~~ - extrait vers https://github.com/etalab/transport-site/issues/3156
- [ ] ~~Voir si on peut utiliser des named parameters plutôt que `$1` avec Ecto et Postgres (pas sûr...)~~

### Améliorations à discuter pour la suite

- [x] #3138
- [ ] https://github.com/etalab/transport-site/issues/3156
- [ ] En vue détaillée, afficher le nombre de points par réseaux
- [ ] En vue détaillée, ne pas utiliser un simple hover mais être capable d'aller sur le JDD associé
- [ ] Filtrer par réseau
- [ ] Dissocier les points au même endroit avec DeckGL (picking)
- [ ] Optimiser la vue détaillée (ST_CONTAINS)

**Comment by thbar** [comment]
Suffisamment bon pour le moment, on ré-ouvrira si besoin.
