### ISSUE TITLE
Mise en avant de la réutilisation de données : article 122, loi climat et résilience

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3149]
Cette issue suit les tâches à effectuer pour la mise en avant de l'article 122, loi climat et résilience et de l'instauration d'une obligation d'intégration de données.

- [x] Prévoir une page de présentation de l'initiative, des références juridiques. Ajouter un page sur les JDD concernés, indiquer que certaines catégories de données sont concernées par cette obligation #3148
- [x] Archiver les `custom_tags` tous les jours dans `DatasetHistory` https://github.com/etalab/transport-site/pull/3155
- [x] Stocker le nombre de JDD concernés par catégorie de manière quotidienne https://github.com/etalab/transport-site/pull/3158
- [x] Ajout d'un filtre lors de la recherche de JDD #3180
- [x] Ajout de tuiles par catégorie de données sur la page dédiée #3183

**Comment by AntoineAugusti** [comment]
On est bons pour un premier jet ! @Benoit-MINT hésite pas à dire si tu vois des choses à ajouter.

**Comment by Benoit-MINT** [comment]
Suite à la décision du CE d'annulation du décret, on va mette en "pause" quelques éléments :
- page loi Climat : suppression après 1er paragraphe du 3ème bloc ;
- bloc sur résultats de recherche : mise au futur + suppression des dates ;
- filtre de recherche inchangé ; 
- suppression des badges sur jdd ;
- syst notification : "les jdd suivants feront l'objet d'une intégration obligatoire dans le cadre de loi C&R"
