### ISSUE TITLE
Remplacer convertisseur GTFS vers NeTEx

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3427]
Objectif : remplacer le convertisseur GTFS vers NeTEx de Hove vers le produit proposé par enRoute.

Le point d'entrée principal côté PAN est [ce job](https://github.com/etalab/transport-site/blob/56662d9cde4f579a8d85016e0907aeed12e2dfdd/apps/transport/lib/jobs/gtfs_to_netex_converter_job.ex#L1), le précédent binaire en charge des conversions est dans [notre Dockerfile](https://github.com/etalab/transport-tools/blob/278f66679537981176f414de8027a86b1b0808ba/Dockerfile#L35) et pourra être supprimé par la suite.

- Documentation de l'API enRoute : https://documenter.getpostman.com/view/9203997/SzmfXwrp
- Clé API : dans Dashlane
- Nom du profil à utiliser : `{"profile": "french"}`

L'API fonctionne en polling (envoie d'une conversion, identifiant unique en retour, vérifier l'état de la conversion puis télécharger le fichier converti). enRoute a indiqué qu'il n'était pas nécessaire qu'on cherche à étaler particulièrement la charge, les gros GTFS (par exemple IDFM) passent aussi (mais peuvent prendre plusieurs minutes).

- [x] Créer un client pour l'API d'EnRoute https://github.com/etalab/transport-site/pull/3542
- [x] Adapter `data_conversion` pour avoir plusieurs convertisseurs par couple de formats https://github.com/etalab/transport-site/pull/3549
- [x] Exécuter parallèlement le convertisseur Hove en local et le convertisseur EnRoute https://github.com/etalab/transport-site/pull/3560
- [x] Utiliser EnRoute comme convertisseur par défaut #3613
- [x] Savoir si on retourne sur Hove en attendant les améliorations du convertisseur EnRoute (ongoing)

**Comment by AntoineAugusti** [comment]
Retour d'EnRoute sur les demandes d'amélioration des conversions.

---

<p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; font-weight: bolder;">Coordonnées géographiques</b></p><blockquote style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; margin-inline: 0.2em 0px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border-left: 1px solid rgb(204, 204, 204); margin-left: 20px; padding: 10px 20px;"><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">les coordonnées géographiques (Centroid/Location)</p></blockquote><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">✅ Le bug est corrigé dans la version du Sprint 102 déployée ce matin.</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pour les autres points, ils ne sont pas très compliqués mais ils sont dans le backlog de Chouette Convert car il y a une question métier pour chacun d’entre eux. Pour résumer, personne n’a défini un mapping officiel entre GTFS et NeTEx sur ces points, donc il faut définir ce qui conviendrait le mieux …</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Nous avons fait un travail presque équivalent sur Chouette (dans les imports/exports) mais les utilisateurs de Chouette peuvent intervenir, disposent de plusieurs attributes quand il peut y avoir une ambiguïté et surtout modifier/enrichir leurs données. Ce qu’une conversion simple ne permet pas 😕</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; font-weight: bolder;">PublicCode</b></p><blockquote style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; margin-inline: 0.2em 0px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border-left: 1px solid rgb(204, 204, 204); margin-left: 20px; padding: 10px 20px;"><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">l'éventuel identifiant public de l'arrêt (PublicCode)</p></blockquote><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Nous essayons depuis longtemps d’obtenir un avis sur la correspondance entre GTFS<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">stop_code</tt><span> </span>/<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">platform_code</tt><span> </span>et NeTEx<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">PublicCode</tt><span> </span>/<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">PlateCode</tt>. Selon les discussions et les usages, le GTFS Stop Code contient parfois plus un PublicCode et parfois plus .. un PlateCode. Parfois le GTFS Plaform Code est utlisé comme NeTEx Public Code 😕</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Le profil France ne précise pas grand chose sur la question<span> </span><a href="https://normes.transport.data.gouv.fr/normes/netex/arrets/#zone-dembarqueme" title="smart-link" class="fa91xkdu" rel="noopener noreferrer" target="_blank" style="user-select: initial; cursor: pointer; box-sizing: content-box; background-repeat: no-repeat; text-decoration: none; background-color: initial; color: rgb(54, 127, 238);">https://normes.transport.data.gouv.fr/normes/netex/arrets/#zone-dembarqueme</a>. Dans Chouette, nous avons deux champs séparés pour gérer les deux cas.</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Donc si Chouette Convert fait une conversion, ca sera arbitrairement à destination de<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">PublicCode</tt><span> </span>ou de<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">PlateCode</tt>. Mais lequel ?</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; font-weight: bolder;">Accessibility Assessment</b></p><blockquote style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; margin-inline: 0.2em 0px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border-left: 1px solid rgb(204, 204, 204); margin-left: 20px; padding: 10px 20px;"><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">les informations d'accessibilité (AccessibilityAssessment)</p></blockquote><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pareil, on peut expliquer à Chouette Convert un mapping mais .. lequel ?</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Côté GTFS, on a GTFS Trip<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">wheelchair_accessible</tt><span> </span>and GTFS Stop<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">wheelchair_boarding</tt>. Côté NeTEx nous avons<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">AccessibilityAssessment</tt>/<tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">MobilityImpairedAccess</tt><span> </span>et<span> </span><tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">AccessibilityAssessment</tt>/<tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">AccessibilityLimitation</tt>/<tt style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">WheelchairAccess</tt>. Pour l’instant, le mapping que nous avons identifié est:</p><div class="fasaryyh" style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
GTFS wheelchair_boarding/wheelchair_accessible | MobilityImpairedAccess
-- | --
0 / empty | unknown
1 | yes
2 | no

</div><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Mais on ne sait pas ce qui conviendrait vraiment dans le cas général.</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; font-weight: bolder;">Transport Mode</b></p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pour définir un Quay/TransportMode par défaut, Chouette Convert peut utiliser le TransportMode des lignes associées. Mais .. il faut qu’il faut qu’il y ait consensus dans ces lignes sur le dit TransportMode. Et surtout cela a un impact non négligeable sur les performances. Car il faut lire l’ensemble des passages (GTFS stop_times) avant de pouvoir déduire cette information 😕</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Nous avons mis de côté l’attribut parce que le fait qu’il soit calculé lui donne peu de valeur (= le consommateur peut faire de même, et surement mieux) et l’impact en performance ne donnait pas plus envie de le calculer.</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; font-weight: bolder;">StopPlaceType</b></p><blockquote style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; margin-inline: 0.2em 0px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border-left: 1px solid rgb(204, 204, 204); margin-left: 20px; padding: 10px 20px;"><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat;">StopPlaceType sur l'objet StopPlace). Cette information est d'ailleurs obligatoire dans le profil FR.</p></blockquote><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Alors .. la on ne sait pas quoi faire. Mettre une valeur par défaut ? Quel intérêt du coup ?</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; font-weight: bolder;">Conclusion</b></p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Globalement peu de difficultés techniques … une fois l’arbitrage métier reálisé. Donc si vous avez un avis sur chacun des points, on est preneur. Je transmets à Christophe Duquesne une copie des points pour voir s’il a un avis éclairé sur certains.</p><p style="user-select: initial; cursor: inherit; box-sizing: content-box; background-repeat: no-repeat; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">NB: les deux derniers points mettent en évidence la limite entre conversion depuis le GTFS et concepts rendus obligatoires dans le profil.</p>

**Comment by AntoineAugusti** [comment]
Ma réponse [au ticket](https://enroute.atlassian.net/servicedesk/customer/portal/1/SUPPORT-1124).

---

Bonjour Alban,

Merci pour ton retour détaillé ! Je partage globalement tes réserves sur le fait qu’une conversion automatique avec une information moins détaillée en entrée et sans document de mapping officiel est un exercice périlleux. Ceci permet de soulever des questions intéressantes pour le GT7 qui vont améliorer sans aucun doute le caractère opérationnel de la spécification NeTEx.

Dans l’immédiat notre réutilisateur principal pour ces conversions (JungleBus qui réalise un outil permettant d'éditer/améliorer les informations relatives à l’accessibilité) était demandeur des champs concernant la localisation et l’accessibilité dans les conversions.

## Règles de conversions de Hove

Je te partage [le document de Hove indiquant les règles de conversion NTFS (leur format) vers NeTEx France](https://github.com/hove-io/transit_model/blob/master/documentation/ntfs_to_netex_france_specs.md). Il explique les règles suivies pour les champs AccessibilityAssessment, StopPlaceType et TransportMode entre autres.

La règle pour l'accessibilité semble relativement simple à mettre en oeuvre et peu génératrice de débats mais c’est moins net pour le reste. Il y a, comme tu l’indiques, un coût de performance important pour déduire le mode de transport desservant un arrêt/un quai quand on doit analyser les trips/stop_times d’un GTFS.

Les règles de conversion adoptées par Hove nous paraissent aller dans le bon sens tant que le GT7 n'émet pas une position inverse.

À disposition pour en discuter si nécessaire.

**Comment by AntoineAugusti** [comment]
Je vais clore ce ticket.

EnRoute a commencé à améliorer la qualité des conversions NeTEx et nous avons jugé qu'il n'était pas nécessaire de retourner aux conversions Hove pour le moment.

On garde les conversions côte à côte encore, pour se laisser de la flexibilité et la possibilité de revoir notre position.

Sinon, dans quelques on espèce que les conversions NeTEx EnRoute auront une bonne complétude et on pourra alors supprimer le code de conversion propre à Hove.

**Comment by jthiard** [comment]
Bonjour,
je travaille avec JungleBus sur les outils de collecte de donnée d'Accessibilité (société Someware).
Je ne sais pas si ce point a été remonté à enRoute, mais il arrive que la conversion NeTEx ait beaucoup moins d'arrêts que le GTFS.

Ex: Réseau STAR de Rennes Métropole : https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-de-bus-et-de-metro-du-reseau-star-au-format-gtfs

- Dans le GTFS tous les arrêts bus / métro sont présents.
- Dans le NeTEx seuls les arrêts de métro sont présents.

**Comment by thbar** [comment]
@jthiard merci pour le retour ! On va se faire un ticket spécifique je pense pour ne pas perdre cela, c'est précieux.

**Comment by thbar** [comment]
@jthiard vous pouvez suivre la suite ici https://github.com/etalab/transport-site/issues/3732, j'ai préféré créer un ticket pour ne pas qu'on perde l'info en bas de ticket ici !
