### ISSUE TITLE
[EPIC] Solidifier le processus de déploiement

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3688]
Comme discuté avec @AntoineAugusti notamment, je note ici les points d'améliorations qu'on pourra envisager pour les livraisons.

### Préambule

Distinction compile-time vs runtime: en Elixir aujourd'hui les fichiers `config.exs`, `prod.exs` (utilisé autant pour le staging que pour la vraie production) sont pris en compte au moment de la compilation.

Le fichier `runtime.exs` lui est pris en compte au moment du runtime.

- https://github.com/etalab/transport-site/blob/master/config/prod.exs
- https://github.com/etalab/transport-site/blob/master/config/runtime.exs
- https://github.com/etalab/transport-site/blob/master/config/config.exs

Il se trouve qu'aujourd'hui le compile-time et le runtime se produisent tous les deux sur CleverCloud, avec les variables d'environnement "sous le coude". Le compile-time a lieu dans une machine dite "de build", tandis que le runtime tourne dans un container d'execution.

Les variables sont injectées dans les deux, mais les deux containers peuvent être dimensionnés différemment (pour des raisons de coût).

Ce méli-mélo un peu historique introduit certaines complexités qu'il va falloir résoudre à un moment (voir plus bas) si on veut améliorer les choses.

### 1. Configuration applicative pas assez "solide"

La configuration a petit à petit été déplacée vers `runtime.exs` volontairement pour permettre la mise en place (à terme) de "releases" Elixir, qui présentent certains avantages (voir le point 2 - compilations déportées, et le préambule)
- https://github.com/etalab/transport-site/issues/1817

Pour se faire, on a déplacé des configurations de `config.exs` et/ou `prod.exs` (qui sont compilées vers `runtime.exs`.

Le souci qui en résulte est qu'on peut découvrir un peu trop tard des soucis, avec:
- ou bien un déploiement qui bloque (blue green) car il manque une variable 
- ou bien (pire) un déploiement qui passe, mais qui serait dysfonctionnel

Le dernier cas en date est le suivant:
- https://github.com/etalab/transport-site/pull/3686

(mais il y a eu d'autres épisodes et c'est bien normal, ce qu'on a fait est un peu trop fragile)

Il est important de remettre les choses en "évaluation runtime" pour pouvoir dissocier l'environnement de build et de runtime (voir préambule et voir point 2), mais il faut qu'on améliore cela pour empêcher ce type d'incident assez frustrant / stressant.

**Une recette que j'avais imaginé est la suivante**: packager la totalité de `runtime.exs` mais sous forme de méthode dans un module, beaucoup plus facile à tester, et stubber par exemple l'environnement via une petite behaviour.

Le `runtime.exs` ne ferait qu'appeler à ce stade ce module testé, en passant en paramètre la table d'ENV réelle.

De cette façon testabilité importante, détection des problèmes de production / staging dès le CI avec des tests associés, et moins de stress.

En découle la tâche suivante (on créera un ticket le temps venu)

- [ ] Refactorer `runtime.exs` en un module type `ApplicationConfig`, qui sera mis sous test complètement et qui assertera sur la config, avec notamment un `ENV` moxé

### 2. Modèle de déploiement à revoir

Actuellement (voir préambule), le déploiement est fait comme suit:
- un container de build sur CleverCloud fait tourner notre image Docker, qui compile la totalité du source de zéro (sans cache, et assez lent) ; on pourrait techniquement mettre en place du cache mais en sortant de Docker la dernière fois que j'ai regardé, chose que je ne souhaite pas faire (le freezing des versions dans Docker tel qu'on le fait est très efficace et utile)
- ce container de build injecte déjà les variables d'environnement (avalées par `prod.exs` et éventuellement `config.exs` si il reste des traces encore)
- le container résultant est ensuite déployé en mode "runtime"

Le souci principal de ce modèle est le temps de déploiement (proche des 15 minutes), pour les raisons suivantes:
- c'est lent, on a le temps de passer à autre chose et d'être pris au dépourvu en cas d'incident (ex: on est parti, ou en réunion...)
- en cas de pépin avec un impact réel, on mettrait un peu trop longtemps à notre goût à déployer un fix
- si il faut faire du "trial and error" sur un correctif, on prend encore plus de délai et c'est encore moins confortable

On souhaiterait sur 2024 si possible traiter ce souci tant qu'on est un peu à l'aise (pas d'incident majeur jusque là).

Les solutions possibles sont:
- https://github.com/etalab/transport-site/issues/1817 travailler avec des releases : par exemple générées depuis GitHub et pushées vers un S3, puis le pull de CleverCloud récupère la bonne version (ex: on pourrait les nommer avec le commit dedans, qui est déjà dispo comme variable d'env de l'autre côté ; évidemment il faudrait aussi gérer les branches etc, ça peut être un peu plus compliqué) - pour faire ça, il faut solidifier la configuration (voir partie 1) et personnaliser un peu le processus de build. C'est l'option la plus légère
- créer dès la GitHub action une image complète prête, et ensuite travailler du côté de CleverCloud pour dynamiquement récupérer cela ; c'est un peu plus lourd pour différentes raisons

Je préfère nettement la première solution, qui sera plus rapide en exécution théorique, moins consommatrice de bande passante si c'est bien fait, et qui permet d'historiser nos builds aussi assez facilement et à coût nul.

Etapes si on va dans ce sens:
- [ ] Commencer à créer des releases en local (modifier la configuration pour être 100% runtime pour de bon)
- [ ] Faire une GitHub action de test qui va faire de même et stocker le tout (sans credentials) dans un registry
- [ ] Faire un test de déploiement un peu à la main (ça pourrait en pratique être fait sur CleverCloud ou même sur ScaleWay, car du coup le fonctionnement sera plus agnostique par rapport à la plateforme)
- [ ] Travailler au déploiement automatisé côté CleverCloud

**Comment by vdegove** [comment]
Il y a des appels directs à des variables d’environnements dans d’autres fichiers que ceux cités ici, par exemple dans `config/datagouvfr.exs` ou `config/mail.exs`. Qu’est-ce qu’on en fait ? C’est pas gênant ?

Sujet un peu connexe : on pourrait pas en profiter pour basculer entièrement sur `dev.secret.exs` au lieu d’avoir également un fichier `.env` ?

**Comment by AntoineAugusti** [comment]
> on pourrait pas en profiter pour basculer entièrement sur dev.secret.exs au lieu d’avoir également un fichier .env ?

je n'ai pas de fichier `.env` sur ma machine. Le code ne lit pas le fichier `.env` mais accède seulement à des variables d'environnement. Peut-être que ton terminal lit automatiquement le `.env` pour le transformer en variable d'env ?

**Comment by vdegove** [comment]
> je n'ai pas de fichier .env sur ma machine.

Alors moi non plus, je n’ai pas de fichier .env, mais il y a un fichier .env.example, et j’avais cru comprendre que pour développer certaines parties du site, on devait s’en servir (en le copiant sur un fichier .env et en remplissant les variables d’environnement), car tout n’avait pas été migré vers dev.secret.exs. Si ce n’est pas le cas, autant le supprimer.

**Comment by thbar** [comment]
> Alors moi non plus, je n’ai pas de fichier .env, mais il y a un fichier .env.example

C'est poubelle effectivement je confirme - on peut se débrouiller à 100% mais il y a encore peu longtemps ce n'était pas le cas.

La partie "MinIO S3 local" par exemple est peu documentée mais très utile pour mes travaux de masse.

**Comment by thbar** [comment]
> Il y a des appels directs à des variables d’environnements dans d’autres fichiers que ceux cités ici, par exemple dans config/datagouvfr.exs ou config/mail.exs. Qu’est-ce qu’on en fait ? C’est pas gênant ?

Tout ça est "avalé" par le `config.exs` et donc intégré à compile-time. Il faudra effectivement refactorer tout ça.

Mais pas d'urgence hein :-)

**Comment by thbar** [comment]
> Sujet un peu connexe : on pourrait pas en profiter pour basculer entièrement sur dev.secret.exs au lieu d’avoir également un fichier .env ?

Réponse oui clairement - il faut s'assurer que le template reste bien à jour et documenté !

**Comment by AntoineAugusti** [comment]
Suppression de `.env.example` ici https://github.com/etalab/transport-site/pull/3690

**Comment by thbar** [comment]
Je progresse sur ce point:
- https://github.com/etalab/transport-site/pull/5481
- https://github.com/etalab/transport-site/pull/5489 fix au passage
- et un travail en cours pour interdire les appels à `System.get_env` et similaire dans les fichiers compilés

**Comment by thbar** [comment]
Je déploie la suite:
- #5521
- #5522

J'ai mis en place un check credo pour interdire les appels à `x.get_env` etc hors "runtime exs". Pour l'instant je l'ai mis en warning.

J'avais 48 warnings et je suis descendu à environ 28 avec les 2 PR, je vais aller traiter la suite.
