### ISSUE TITLE
Améliorer l’UX de l’édition de jeu de données et de resources asociées dans l’espace producteur

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3799]
En tant que producteur, je veux gérer mes jeux de données et resources associées de manière ergonomique, en ayant une bonne visualisation de l’existant au moment d’éditer, supprimer ou rajouter des resources.

## État des lieux

Aujourd’hui, dans l’espace producteur, on a ces cartes là pour éditer un jeu de données (seule la mise en place d’un logo personnalisée est possible) et les resources associées (suppression, édition, rajout d’une nouvelle resource) :

![image](https://github.com/etalab/transport-site/assets/15861435/eb5aa658-767a-4b65-96e6-1a675b54cf2a)

Le bouton éditer renvoie vers `espace_producteur/datasets/{id}/edit` :
![image](https://github.com/etalab/transport-site/assets/15861435/3eed2bae-b815-47ba-b6c6-a9fb37c9ce22)

Et les 3 boutons permettent d’éditer les resources, Modifier va sur `resources/update/datasets/{datagouv_id}/resources`, Ajouter vers `resources/update/datasets/{datagouv_id}/resources/_new_resource` et supprimer vers `resources/update/datasets/{datagouv_id}/resources?mode=delete` (routes non namespacées à l’espace producteur) :
![image](https://github.com/etalab/transport-site/assets/15861435/bbfab37d-d90e-441f-8a9b-e04265e03c28)
![image](https://github.com/etalab/transport-site/assets/15861435/4723fb44-71ef-4881-a8b5-18b4dac9d429)
![image](https://github.com/etalab/transport-site/assets/15861435/264ed4f9-8620-4184-b6ac-63cae94e75a5)

## Problèmes

- C’est peu clair sur la carte sur l’espace producteur de ce que fait chaque bouton : par exemple, on pourrait s’attendre que derrière le bouton principal «éditer» on puisse accéder à l’édition des resources, et non seulement du logo ; supprimer peut peut-être vouloir dire supprimer le dataset…
- On peut du coup se tromper d’endroit, et c’est peu ergonomique d’avoir des pages séparées chacune listant les resources pour l’édition et la suppression de celles-ci, ou de rajouter une resource sans avoir la liste des resources existantes devant soit.

## Solution proposée

Rassembler sur une page unique d’édition de jeu de données :
- La liste des resources existantes, avec pour chacune un bouton d’édition et de suppression, et un lien vers le PAN
- Un bouton pour rajouter une nouvelle resource (avec du coup, la liste de resources déjà existantes juste au dessus)
- L’édition de logo

Au passage, on pourrait du coup tout namespacer et nettoyer le contrôleur principal de resources, en ne gardant dessus que ce qui est sur la partie publique du PAN.

## Points d’attention / de vigilance

- Faire en sorte de réutiliser le code existant au max
- Le code existant va aller chercher des infos sur datagouv pour s’assurer d’avoir des versions à jour du dataset, de son nom, de ses resources existantes : bien réfléchir à ce qui est pertinent d’afficher à partir de l’info en base et de l’info live sur datagouv.
- Vérifier avec les chargés de déploiement les infos qui doivent apparaître sur cette page :
 - Remettre les avertissements d’usage pour dire d’éditer les resources existantes plutôt que rajouter, lien vers la doc
 - Plus d’informations sur les resources issues de la base ? (Exemple : metadonnées) Sans que ça soit trop compliqué de les faire apparaître.
 - Liens vers les pages publiques du PAN et vers la page datagouv ?
 - Faire attention à l’autorisation : peut-être limiter l’accès aux pages si on est pas producteur de ce dataset en particulier.

## Bonus

À voir si on peut pas aussi :
- Introduire un lien depuis la page publique du PAN du dataset si le producteur est connecté
- Laisser les admins accéder à l’édition de tous les datasets

## Page d’édition de datasets à supprimer ?

En fouillant le contrôleur resources, j’ai trouvé le chemin vers `resources/update/datasets/` qui donne cette page :

![image](https://github.com/etalab/transport-site/assets/15861435/557d75d1-c78a-43f0-b2ca-ae7cb58c813d)

Ça semble être un pré-espace producteur, à mon avis on peut supprimer.

## TODO TECH

- [ ] Améliorer la vue d’édition de datasets, en mettant une liste pour éditer / supprimer des resources liées et un bouton pour ajouter un dataset
- [ ] Retirer les liens de la page globale de l’espace producteur
- [ ] Supprimer les anciennes pages de listes de resources associées à un dataset (suppression, édition) et routes associées
- [ ] Faire un contrôleur spécifique namespacé pour l’édition de resources dans l’espace producteur et y déplacer le code existant
