### ISSUE TITLE
Split language files per view

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#77]
In order to reduce rebase time.

**Definition of done**

- [x] Use ```alert.pot``` (for flashes, etc.) #93 
- [x] Use ```user.pot``` #79
- [x] Use ```page.pot``` #94
